"""Añade modelos de rentabilidad y ruta de cambio de contraseña

Revision ID: 202d5a46cae3
Revises: 6dd76a5ee0cf
Create Date: 2025-08-06 02:06:28.468765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202d5a46cae3'
down_revision = '6dd76a5ee0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_contract_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_contract', ['service_contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_period', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_contract_id')

    op.drop_table('service_contract')
    op.drop_table('client')
    # ### end Alembic commands ###
