"""Añadir telefono y rut a User

Revision ID: 28150fbc5852
Revises: 3dd5edc8144a
Create Date: 2025-07-30 13:00:27.743631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28150fbc5852'
down_revision = '3dd5edc8144a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rut', sa.String(length=12), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['rut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('rut')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
