"""Crear estructura inicial con roles

Revision ID: 3dd5edc8144a
Revises: 
Create Date: 2025-07-17 15:25:25.160382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd5edc8144a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('shift_type', sa.String(length=10), nullable=True),
    sa.Column('shift_start_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('work_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('patente', sa.String(length=10), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('trip_origin', sa.String(length=100), nullable=False),
    sa.Column('trip_destination', sa.String(length=100), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('work_period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_period_id'], ['work_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('work_period')
    op.drop_table('user')
    # ### end Alembic commands ###
