"""Añadir status a WorkPeriod

Revision ID: 6dd76a5ee0cf
Revises: 28150fbc5852
Create Date: 2025-07-30 14:32:09.065033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd76a5ee0cf'
down_revision = '28150fbc5852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='activo'))
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_period', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
